# Generated by Django 6.0 on 2026-01-12 21:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "customer_email_normalized",
                    models.EmailField(db_index=True, max_length=254),
                ),
                ("shipping_name", models.CharField(max_length=255)),
                ("shipping_address_line1", models.CharField(max_length=255)),
                (
                    "shipping_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("shipping_city", models.CharField(max_length=255)),
                ("shipping_postal_code", models.CharField(max_length=64)),
                ("shipping_country", models.CharField(max_length=64)),
                ("shipping_phone", models.CharField(max_length=64)),
                ("billing_same_as_shipping", models.BooleanField(default=True)),
                (
                    "billing_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_city",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_postal_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "billing_country",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "billing_phone",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("is_claimed", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CUSTOMER_REQUEST", "Customer request"),
                            ("PAYMENT_FAILED", "Payment failed"),
                            ("PAYMENT_EXPIRED", "Payment expired"),
                            ("OUT_OF_STOCK", "Out of stock"),
                            ("SHOP_REQUEST", "Shop request"),
                            ("FRAUD_SUSPECTED", "Fraud suspected"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("ADMIN", "Admin"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("PAID", "Paid"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claimed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMMITTED", "Committed"),
                            ("RELEASED", "Released"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "release_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("PAYMENT_EXPIRED", "Payment Expired"),
                            ("CUSTOMER_REQUEST", "Customer Request"),
                            ("ADMIN_CANCEL", "Admin Cancel"),
                            ("OUT_OF_STOCK", "Out Of Stock"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_reservations",
                        to="products.product",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_reservations",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer_email_normalized"], name="orders_email_norm_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["is_claimed", "customer_email_normalized"],
                name="orders_claimed_email_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryreservation",
            index=models.Index(
                fields=["status", "expires_at"], name="inv_res_status_exp_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryreservation",
            constraint=models.UniqueConstraint(
                fields=("order", "product"),
                name="inventory_reservation_order_product_uniq",
            ),
        ),
    ]
