# Generated by Django 6.0 on 2026-01-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "permissions": [
                    ("can_fulfill", "Can fulfill orders (ship/deliver)"),
                    ("can_cancel_admin", "Can cancel orders as admin"),
                ]
            },
        ),
    ]
