# Generated by Django 6.0 on 2026-01-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUSTOMER_REQUEST", "Customer request"),
                    ("PAYMENT_FAILED", "Payment failed"),
                    ("PAYMENT_EXPIRED", "Payment expired"),
                    ("OUT_OF_STOCK", "Out of stock"),
                    ("SHOP_REQUEST", "Shop request"),
                    ("FRAUD_SUSPECTED", "Fraud suspected"),
                    ("ADMIN_CANCELLED", "Admin cancelled"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
