# Generated by Django 6.0 on 2026-01-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_guest_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUSTOMER_REQUEST", "Customer request"),
                    ("PAYMENT_FAILED", "Payment failed"),
                    ("PAYMENT_EXPIRED", "Payment expired"),
                    ("OUT_OF_STOCK", "Out of stock"),
                    ("SHOP_REQUEST", "Shop request"),
                    ("FRAUD_SUSPECTED", "Fraud suspected"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("ADMIN", "Admin"),
                    ("SYSTEM", "System"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="InventoryReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMMITTED", "Committed"),
                            ("RELEASED", "Released"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "release_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PAYMENT_FAILED", "Payment failed"),
                            ("PAYMENT_EXPIRED", "Payment expired"),
                            ("CUSTOMER_REQUEST", "Customer request"),
                            ("ADMIN_CANCEL", "Admin cancel"),
                            ("OUT_OF_STOCK", "Out of stock"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_reservations",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_reservations",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="inventoryreservation",
            constraint=models.UniqueConstraint(
                fields=("order", "product"),
                name="inventory_reservation_order_product_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryreservation",
            index=models.Index(
                fields=["status", "expires_at"],
                name="inv_res_status_exp_idx",
            ),
        ),
    ]
