# Generated by Django 6.0 on 2025-12-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("PAID", "Paid"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELED", "Canceled"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
