# Generated by Django 6.0 on 2026-01-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_cancel_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="guest_access_token_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_access_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
