# Generated by Django 6.0 on 2025-12-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(),
        ),
    ]
