# Generated by Django 6.0 on 2026-03-08 17:32

import products.models
import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_remove_product_product_price_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to=products.models._product_gallery_upload_to),
        ),
    ]
