# Generated by Django 6.0 on 2026-03-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(help_text="Stable machine-readable identifier, e.g. 'standard', 'reduced', 'zero'.", max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional notes visible only in the admin.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tax Class',
                'verbose_name_plural': 'Tax Classes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('PLN', 'Polish Zloty')], default='EUR', help_text='ISO 4217 currency code.', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='price_net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net (pre-tax) price of the product.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_class',
            field=models.ForeignKey(blank=True, help_text='Tax classification applied to this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.taxclass'),
        ),
    ]
