# Generated by Django 6.0 on 2026-03-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_pricing_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxclass',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tax rate as a percentage (e.g. 23 for 23 %). Leave blank for 0 %.', max_digits=6, null=True),
        ),
    ]
