# Generated by Django 6.0 on 2026-03-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_taxclass_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Gross (post-tax) price — derived from price_net_amount via the tax resolver on every save.  Read-only; do not set directly.', max_digits=10, null=True),
        ),
    ]
