# Generated by Django 6.0 on 2026-03-26 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0009_order_supplier_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=50)),
                ('service_code', models.CharField(max_length=50)),
                ('carrier_name_snapshot', models.CharField(max_length=255)),
                ('service_name_snapshot', models.CharField(max_length=255)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LABEL_CREATED', 'Label created'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('FAILED_DELIVERY', 'Failed delivery'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('label_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('receiver_snapshot', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('raw_status', models.CharField(blank=True, max_length=64, null=True)),
                ('normalized_status', models.CharField(choices=[('PENDING', 'Pending'), ('LABEL_CREATED', 'Label created'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('FAILED_DELIVERY', 'Failed delivery'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('external_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order', 'status'], name='shipping_sh_order_i_242975_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['provider_code', 'tracking_number'], name='shipping_sh_provide_283303_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', 'normalized_status'], name='shipping_sh_shipmen_f64913_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['external_event_id'], name='shipping_sh_externa_937057_idx'),
        ),
    ]
