# Generated by Django 6.0 on 2025-12-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_unique_category_name_per_parent_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="category_parent_not_self",
        ),
    ]
