# Generated by Django 6.0 on 2025-12-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_remove_category_category_parent_not_self"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_parent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="category_parent_not_self",
            ),
        ),
    ]
