# Generated by Django 6.0 on 2025-12-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_category_is_parent_category_category_parent_not_self"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="category_parent_not_self",
        ),
    ]
