from __future__ import annotations


DEMO_USERS = [
    {
        "key": "superuser",
        "email": "admin@shopwise.test",
        "password": "DemoAdmin123!",
        "first_name": "Marta",
        "last_name": "Kralova",
        "is_staff": True,
        "is_superuser": True,
        "email_verified": True,
    },
    {
        "key": "staff",
        "email": "staff@shopwise.test",
        "password": "DemoStaff123!",
        "first_name": "David",
        "last_name": "Urban",
        "is_staff": True,
        "is_superuser": False,
        "email_verified": True,
    },
    {
        "key": "customer_1",
        "email": "alice.walker@shopwise.test",
        "password": "DemoCustomer123!",
        "first_name": "Alice",
        "last_name": "Walker",
        "is_staff": False,
        "is_superuser": False,
        "email_verified": True,
    },
    {
        "key": "customer_2",
        "email": "martin.novak@shopwise.test",
        "password": "DemoCustomer123!",
        "first_name": "Martin",
        "last_name": "Novak",
        "is_staff": False,
        "is_superuser": False,
        "email_verified": True,
    },
]


DEMO_TAX_CLASSES = [
    {
        "key": "vat_21",
        "code": "vat-21",
        "name": "VAT 21%",
        "description": "Standard VAT rate for showcase catalog items.",
        "rate": "21.0000",
    },
    {
        "key": "vat_12",
        "code": "vat-12",
        "name": "VAT 12%",
        "description": "Reduced VAT rate for selected showcase catalog items.",
        "rate": "12.0000",
    },
    {
        "key": "vat_0",
        "code": "vat-0",
        "name": "VAT 0%",
        "description": "Zero VAT rate for tax-exempt showcase catalog items.",
        "rate": "0.0000",
    },
]


DEMO_SUPPLIER = {
    "key": "default_supplier",
    "lookup": {"company_id": "SHOPWISE-DEMO-001"},
    "defaults": {
        "name": "Shopwise Demo Supply",
        "company_id": "SHOPWISE-DEMO-001",
        "vat_id": "CZSHOPWISE001",
        "email": "supply@shopwise.test",
        "phone": "+420555123456",
        "is_active": True,
    },
    "addresses": [
        {
            "key": "billing_hq",
            "label": "Billing HQ",
            "street_line_1": "Demo Avenue 12",
            "street_line_2": "Holesovice",
            "city": "Prague",
            "postal_code": "17000",
            "country": "CZ",
            "is_default_for_orders": True,
        },
        {
            "key": "operations",
            "label": "Operations",
            "street_line_1": "Warehouse Park 7",
            "street_line_2": "",
            "city": "Brno",
            "postal_code": "60200",
            "country": "CZ",
            "is_default_for_orders": False,
        },
    ],
    "payment_details": [
        {
            "key": "primary_account",
            "label": "Primary CZK Account",
            "bank_name": "Ceska sporitelna",
            "account_number": "123456789/0800",
            "iban": "CZ6508000000001234567899",
            "swift": "GIBACZPX",
            "is_default_for_orders": True,
        }
    ],
}


DEMO_CATEGORIES = [
    {"key": "electronics", "name": "Electronics"},
    {"key": "grocery", "name": "Grocery"},
    {"key": "pets", "name": "Pets"},
]


DEMO_PRODUCTS = [
    {
        "key": "wireless_headphones",
        "name": "Wireless Headphones",
        "slug": "wireless-headphones",
        "category_name": "Electronics",
        "tax_class_name": "VAT 21%",
        "price": "2490.00",
        "stock_quantity": 50,
    },
    {
        "key": "mechanical_keyboard",
        "name": "Mechanical Keyboard",
        "slug": "mechanical-keyboard",
        "category_name": "Electronics",
        "tax_class_name": "VAT 21%",
        "price": "3190.00",
        "stock_quantity": 50,
    },
    {
        "key": "usb_c_dock",
        "name": "USB-C Dock",
        "slug": "usb-c-dock",
        "category_name": "Electronics",
        "tax_class_name": "VAT 21%",
        "price": "1890.00",
        "stock_quantity": 50,
    },
    {
        "key": "smart_speaker",
        "name": "Smart Speaker",
        "slug": "smart-speaker",
        "category_name": "Electronics",
        "tax_class_name": "VAT 21%",
        "price": "1590.00",
        "stock_quantity": 50,
    },
    {
        "key": "portable_ssd",
        "name": "Portable SSD",
        "slug": "portable-ssd",
        "category_name": "Electronics",
        "tax_class_name": "VAT 21%",
        "price": "2190.00",
        "stock_quantity": 50,
    },
    {
        "key": "organic_pasta",
        "name": "Organic Pasta",
        "slug": "organic-pasta",
        "category_name": "Grocery",
        "tax_class_name": "VAT 12%",
        "price": "79.00",
        "stock_quantity": 50,
    },
    {
        "key": "olive_oil",
        "name": "Olive Oil",
        "slug": "olive-oil",
        "category_name": "Grocery",
        "tax_class_name": "VAT 12%",
        "price": "189.00",
        "stock_quantity": 50,
    },
    {
        "key": "granola_mix",
        "name": "Granola Mix",
        "slug": "granola-mix",
        "category_name": "Grocery",
        "tax_class_name": "VAT 12%",
        "price": "129.00",
        "stock_quantity": 50,
    },
    {
        "key": "green_tea",
        "name": "Green Tea",
        "slug": "green-tea",
        "category_name": "Grocery",
        "tax_class_name": "VAT 12%",
        "price": "99.00",
        "stock_quantity": 50,
    },
    {
        "key": "dark_chocolate",
        "name": "Dark Chocolate",
        "slug": "dark-chocolate",
        "category_name": "Grocery",
        "tax_class_name": "VAT 12%",
        "price": "69.00",
        "stock_quantity": 50,
    },
    {
        "key": "dog_food_premium",
        "name": "Dog Food Premium",
        "slug": "dog-food-premium",
        "category_name": "Pets",
        "tax_class_name": "VAT 12%",
        "price": "799.00",
        "stock_quantity": 50,
    },
    {
        "key": "cat_litter_pro",
        "name": "Cat Litter Pro",
        "slug": "cat-litter-pro",
        "category_name": "Pets",
        "tax_class_name": "VAT 12%",
        "price": "249.00",
        "stock_quantity": 50,
    },
    {
        "key": "pet_shampoo",
        "name": "Pet Shampoo",
        "slug": "pet-shampoo",
        "category_name": "Pets",
        "tax_class_name": "VAT 21%",
        "price": "159.00",
        "stock_quantity": 50,
    },
    {
        "key": "chew_toy_rope",
        "name": "Chew Toy Rope",
        "slug": "chew-toy-rope",
        "category_name": "Pets",
        "tax_class_name": "VAT 0%",
        "price": "119.00",
        "stock_quantity": 50,
    },
    {
        "key": "pet_bowl_set",
        "name": "Pet Bowl Set",
        "slug": "pet-bowl-set",
        "category_name": "Pets",
        "tax_class_name": "VAT 0%",
        "price": "299.00",
        "stock_quantity": 50,
    },
]