# Generated by Django 6.0 on 2026-01-14 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=128)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("customer", "Customer"),
                            ("admin", "Admin"),
                        ],
                        max_length=16,
                    ),
                ),
                ("actor_identifier", models.CharField(blank=True, max_length=128, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("context", models.JSONField(default=dict)),
                ("scope_key", models.CharField(blank=True, max_length=128, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["entity_type", "entity_id"], name="audit_entity_type_id_idx"),
                    models.Index(fields=["created_at"], name="audit_created_at_idx"),
                ],
            },
        ),
    ]
