# Generated by Django 6.0 on 2026-01-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="auditlog_au_entity__aa947c_idx",
            old_name="audit_entity_type_id_idx",
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="auditlog_au_created_778b93_idx",
            old_name="audit_created_at_idx",
        ),
    ]
