# Generated by Django 6.0 on 2026-01-17 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auditlog",
            "0002_rename_audit_entity_type_id_idx_auditlog_au_entity__aa947c_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["action"], name="auditlog_au_action_92e229_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["actor_type"], name="auditlog_au_actor_t_e2dc86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["action", "created_at"], name="auditlog_au_action_1cc966_idx"
            ),
        ),
    ]
