# Generated by Django 6.0 on 2026-01-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="unique_payment_per_order",
        ),
    ]
