# Generated by Django 6.0 (choices-only AlterField — no schema change)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_expand_payment_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("DEV_FAKE", "Dev Fake (simulation)"),
                    ("ACQUIREMOCK", "AcquireMock (hosted gateway)"),
                ],
                default="DEV_FAKE",
                max_length=50,
            ),
        ),
    ]
