# Generated by Django 6.0 on 2026-03-09 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('discounts', '0001_initial'),
        ('products', '0010_django_prices_gross_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable promotion name visible in admin reports.', max_length=255)),
                ('code', models.CharField(help_text="Stable machine-readable identifier, e.g. 'summer-2026'. Used for logging and future coupon linkage.", max_length=64, unique=True)),
                ('type', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed')], help_text='PERCENT — relative discount (e.g. 10 %); FIXED — absolute amount off.', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount magnitude. For PERCENT: 0 < value ≤ 100. For FIXED: value > 0.', max_digits=10)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher value = higher priority. Used for conflict resolution in later phases.')),
                ('is_active', models.BooleanField(default=True)),
                ('active_from', models.DateField(blank=True, help_text='Optional start date (inclusive). If blank, promotion is always eligible from the past.', null=True)),
                ('active_to', models.DateField(blank=True, help_text='Optional end date (inclusive). If blank, promotion has no expiry.', null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional internal notes visible to admin users only.')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_targets', to='categories.category')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_targets', to='discounts.promotion')),
            ],
            options={
                'verbose_name': 'Promotion → Category',
                'verbose_name_plural': 'Promotion → Categories',
                'unique_together': {('promotion', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_targets', to='products.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_targets', to='discounts.promotion')),
            ],
            options={
                'verbose_name': 'Promotion → Product',
                'verbose_name_plural': 'Promotion → Products',
                'unique_together': {('promotion', 'product')},
            },
        ),
    ]
