# Generated by Django 6.0 on 2026-03-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_add_promotion_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='amount_scope',
            field=models.CharField(choices=[('NET', 'Net (base price before tax)'), ('GROSS', 'Gross (final customer-visible price)')], default='GROSS', help_text='For FIXED promotions only: whether the fixed amount is deducted from the NET price (base before tax) or the GROSS price (final price the customer sees). Defaults to GROSS (B2C-friendly). Ignored for PERCENT promotions.', max_length=5),
        ),
    ]
