# Generated by Django 6.0 on 2025-12-20 19:38

import discounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0002_discount_category_discount_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="valid_from",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="discount",
            name="valid_to",
            field=models.DateField(default=discounts.models.get_default_valid_to),
        ),
    ]
