# Generated by Django 6.0 on 2026-03-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_add_promotion_amount_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable promotion name visible in admin and customer-facing messages.', max_length=255)),
                ('code', models.CharField(help_text='Stable machine-readable identifier used for logging and offer linkage.', max_length=64, unique=True)),
                ('type', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed')], help_text='PERCENT — relative discount; FIXED — absolute amount off.', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount magnitude.  PERCENT: 0 < value ≤ 100.  FIXED: value > 0.', max_digits=10)),
                ('acquisition_mode', models.CharField(choices=[('AUTO_APPLY', 'Auto-apply'), ('CAMPAIGN_APPLY', 'Campaign apply'), ('MANUAL_ENTRY', 'Manual entry')], default='AUTO_APPLY', help_text='AUTO_APPLY: platform applies automatically. CAMPAIGN_APPLY: triggered by campaign context (URL/UTM/email). MANUAL_ENTRY: customer enters a coupon code (fallback only).', max_length=16)),
                ('stacking_policy', models.CharField(choices=[('EXCLUSIVE', 'Exclusive (no other order-level discounts)'), ('STACKABLE_WITH_LINE', 'Stackable with line-level promotions')], default='EXCLUSIVE', help_text='Controls coexistence with other discounts on the same order. See StackingPolicy docstring for semantics.', max_length=22)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher value = higher priority.  Used for conflict resolution.')),
                ('minimum_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Optional minimum gross order value (before this discount) required for eligibility. Used for threshold / progress-reward scenarios.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('active_from', models.DateField(blank=True, help_text='Optional start date (inclusive).  Blank = no lower bound.', null=True)),
                ('active_to', models.DateField(blank=True, help_text='Optional end date (inclusive).  Blank = no expiry.', null=True)),
                ('is_discoverable', models.BooleanField(default=False, help_text='When True, this promotion can be surfaced in-product as an active benefit (owned-media contextual promotion / messaging hook). Does not affect eligibility logic.')),
                ('description', models.TextField(blank=True, default='', help_text='Optional internal notes or customer-facing benefit description.')),
            ],
            options={
                'verbose_name': 'Order Promotion',
                'verbose_name_plural': 'Order Promotions',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='The customer-facing code or internal campaign token.  Must be non-empty.  For MANUAL_ENTRY this is what the customer types.', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('DELIVERED', 'Delivered'), ('CLAIMED', 'Claimed'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired')], default='CREATED', help_text='Lifecycle status of this offer token.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Master switch.  Inactive offers are not eligible regardless of status.')),
                ('active_from', models.DateField(blank=True, help_text='Optional start date (inclusive).  Blank = no lower bound.', null=True)),
                ('active_to', models.DateField(blank=True, help_text='Optional end date (inclusive).  Blank = no expiry.', null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional internal notes or distribution context.')),
                ('promotion', models.ForeignKey(help_text='The order-level promotion this offer grants access to.', on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='discounts.orderpromotion')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['token'],
            },
        ),
    ]
