# Generated by Django 6.0 on 2025-12-21 17:48

import discounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0003_alter_discount_valid_from_alter_discount_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="valid_from",
            field=models.DateField(default=discounts.models.get_default_valid_from),
        ),
    ]
