# Generated by Django 6.0 on 2026-03-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_id', models.CharField(blank=True, help_text='Business registration number (IČO etc.)', max_length=64)),
                ('vat_id', models.CharField(blank=True, help_text='VAT registration number (DIČ etc.)', max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Only an active supplier is used for new orders. Exactly one supplier must be active at any time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='SupplierAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Optional label, e.g. 'HQ' or 'Prague Office'.", max_length=64)),
                ('street_line_1', models.CharField(max_length=255)),
                ('street_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=64)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2 country code or full name.', max_length=64)),
                ('is_default_for_orders', models.BooleanField(default=False, help_text='Mark exactly one address per supplier as the default for order snapshots. This address is copied into every new order at checkout time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Address',
                'verbose_name_plural': 'Supplier Addresses',
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Optional label, e.g. 'CZK Account' or 'EUR Account'.", max_length=64)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=64)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('swift', models.CharField(blank=True, max_length=32)),
                ('is_default_for_orders', models.BooleanField(default=False, help_text='Mark exactly one payment record per supplier as the default for order snapshots. These details are copied into every new order at checkout time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Payment Details',
                'verbose_name_plural': 'Supplier Payment Details',
            },
        ),
    ]
